### PR TITLE
About Me

### PR DESCRIPTION
**Pull request by ayotola-t**

### CODE REVIEW

**Review by ToluAkin — COMMENTED** [review]
@ayotola-t Is this your submission for task 1?

**Review by adaugochi — COMMENTED** [review]
Remove space on the name of your folder. Instead of this `About Me`, you can name it like this `AboutMe` instead

**Comment by adaugochi** [comment]
Hello, you made use of the wrong PR title. In your task, it was stated that you should name your pull request title like `[6] Product Page using HTML` instead you name yours as `About me`.

To fix this, you have to close the PR and rework your task again and create a new PR. Always ensure you make use of the right pull request title

**Comment by ayotola-t** [comment]
> @ayotola-t Is this your submission for task 1?

Yes it is

**Comment by ayotola-t** [comment]
> Hello, you made use of the wrong PR title. In your task, it was stated that you should name your pull request title like `[6] Product Page using HTML` instead you name yours as `About me`.
> 
> To fix this, you have to close the PR and rework your task again and create a new PR. Always ensure you make use of the right pull request title

Okay will do.

**Pull request closed without merging**
