### PR TITLE
[51] Create Contact Form- Fullstack 

### PR DESCRIPTION
**Pull request by AAOYV2020**
## Task: `create a contact page/form`
- `I created a contact page requesting customer details, providing contact information and a texture with a submit button`

### CODE REVIEW

**Comment by AAOYV2020** [comment]
Screenshot- Anthonia Adollo Contact Page 2020-10-06
[](url)

**Comment by adaugochi** [comment]
Nice, this only fields needed are:

Full Name
Email
Subject
Message input

**Comment by AAOYV2020** [comment]
I have made the changes and updated the push to origin. Thank you!

**Comment by AAOYV2020** [comment]
Screenshot anthoniaAdollo- contact form  2020-10-06

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
