### PR TITLE
Add about me file

### PR DESCRIPTION
**Pull request by Badabee**
## Task: `Upload About Me File`
- Added descriptions about Betty

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Your PR is not properly titled. Kindly name your PR appropriately following the instructions in the task criteria. You ought to have a number in square brackets followed by "About Me". Kindly check the criteria number 10 of your task and see what you are asked to use as PR title or name. Going forward, you have to close this PR and create a new one.

**Comment by adaugochi** [comment]
Also, if you are for Dufuna-Fem, kindly clone this repo https://github.com/Dufuna-CodeCamp/Dufuna-Fem not Dufuna-CodeCamp20

**Comment by adaugochi** [comment]
Ensure you close this PR

**Comment by Badabee** [comment]
I will, thanks.

**Pull request closed without merging**
