### PR TITLE
Loops and Numbers #934

### PR DESCRIPTION
**Pull request by kazeemerinfolami**
## Task: `Loops and Numbers #934`
- `PHP Loops and Numbers`

### CODE REVIEW

**Comment by adaugochi** [comment]
Wrong PR title

**Comment by kazeemerinfolami** [comment]
please Ada how can I fix this?? will I make the PR title change here on Github or on my terminal

**Comment by adaugochi** [comment]
You have to create a new PR

**Comment by kazeemerinfolami** [comment]
do i need to delete this branch?

**Comment by adaugochi** [comment]
No

**Pull request closed without merging**
