### PR TITLE
[DCFS-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by kemysola**
## Task: `Product Page using Html`
- `corrected as advised`
Screen Shot 2021-02-17 at 4 56 59 PM

### CODE REVIEW

**Comment by kemysola** [comment]
Good evening @ToluAkin @adaugochi .All changes and corrections have been done.Please kindly approve .Thank you very much.

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@kemysola Kindly remove the images that are not used in `index.html` from the PR and rename the images used to be descriptive. Well done on the updates done so far.

**Comment by kemysola** [comment]
> @kemysola Kindly remove the images that are not used in `index.html` from the PR and rename the images used to be descriptive. Well done on the updates done so far.

@ToluAkin Good afternoon ma, all changes have been corrected.Please kindly approve ma.

**Comment by ToluAkin** [comment]
@kemysola With the latest push that you just did, you've added other scholar's files to your pull request. Check [here](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1241/files)

**Comment by kemysola** [comment]
> @kemysola With the latest push that you just did, you've added other scholar's files to your pull request. Check [here](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1241/files)

@ToluAkin Kindly advice me ma, on how to correct it ma.Should i checkout to another branch?

**Comment by ToluAkin** [comment]
@kemysola I would advice to close the current pull request, checkout to another branch, and use `git status` to check and know the files that will be added to your pull request. I would advise not to use `git add .` if you have unnecessary files added to your changes that needs to be changed. Use [this](https://devconnected.com/how-to-remove-files-from-git-commit/) in the case you need to remove some file from your commit and you have not pushed it. If you need more clarifications, kindly reach out.

**Comment by kemysola** [comment]
> @kemysola I would advice to close the current pull request, checkout to another branch, and use `git status` to check and know the files that will be added to your pull request. I would advise not to use `git add .` if you have unnecessary files added to your changes that needs to be pushed. Use [this](https://devconnected.com/how-to-remove-files-from-git-commit/) in case you need to remove file(s) from your commit and you have not pushed it. If you need more clarifications, kindly reach out.

@ToluAkin  Thank you very much ma, i really appreciate your assistance ma.

**Pull request closed without merging**
