### PR TITLE
[1] My First Pull Request 

### PR DESCRIPTION
**Pull request by Dawodurahmonn**
## Task: `update About me File`
- `Add description about Rahmon`

### CODE REVIEW

**Comment by adaugochi** [comment]
Hello, you didn't follow the description given in the task on how to name your title. It ought to be named `[1] My First Pull Request` and not `Add about me file`

**Comment by Dawodurahmonn** [comment]
Good day, 
Should I do it again?     On Monday, August 3, 2020, 09:53:30 AM GMT+1, Maryfaith Mgbede <notifications@github.com> wrote:  
 
 


Hello, you didn't follow the description given in the task on how to name your title. It ought to be named [1] My First Pull Request and not Add about me file

**Comment by adaugochi** [comment]
Don't worry, I have been able to update. 
As you proceed, please follow instructions strictly

Well done

**Comment by adaugochi** [comment]
One more thing I need you to correct is for you to rename your named folder. I want you to remove the space between those name.
When you make the correction, do
- Add
- Commit
- Push 

The changes will be updated on your PR

**Pull request closed without merging**
