### PR TITLE
[10] Create & style the customer sign up page using CSS 

### PR DESCRIPTION
**Pull request by KutrCB**
## Task: `Styling sign up page`
- `created a sign up using html
styled the signup page using css`
signup

### CODE REVIEW

**Comment by adaugochi** [comment]
This is not what is on the mockup

**Comment by adaugochi** [comment]
Well done @KutrCB 

This doesn't look aligned. Also, you didn't paste that of mobile view

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@KutrCB I think you should rename `mystyle.css` to something like `signup.css`

**Comment by KutrCB** [comment]
> @KutrCB I think you should rename `mystyle.css` to something like `signup.css`

Done

**Review by ToluAkin — APPROVED** [review]

**Pull request merged**
