### PR TITLE
[58] Develop an E-commerce Database Store

### PR DESCRIPTION
**Pull request by opeyemipeter1759**
## Task: `Name of given task`
- `Changes you made to given task`

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done

Your schema is correct. The table created and also the columns inside it are correct.
But I have a bit of issue.

First, your indentation is too much and not consistence, Example 
image

This one is better, only the first column that is out of place 
image

Same goes for the `insert` query. Only this one looks ok. Expect for the fact that you didn't add spaces after `,`  after listing the names of the column
image

It was difficult reading through your query. Kindly practice writing clean code. A code that is readable by other people that will likely inherit your codebase. You don't want them wondering about

**Review by adaugochi — CHANGES_REQUESTED** [review]
You are yet to fix comment on your PR. This PR is long overdue @opeyemipeter1759

**Comment by opeyemipeter1759** [comment]
Thanks for the alert,

I have not been able to access the tutorial app for some weeks because I have some outstanding payments to make.

As soon as I can make the payment I will get back to the task.

Thank you.

**Comment by adaugochi** [comment]
> Thanks for the alert,
> 
> I have not been able to access the tutorial app for some weeks because I have some outstanding payments to make.
> 
> As soon as I can make the payment I will get back to the task.
> 
> Thank you.
> 
> @adaugochi

Alright

**Comment by adaugochi** [comment]
Kindly update your PR title to the new task title that is on the app. Going forward, I will have to close this PR so you can then create a new one

**Pull request closed without merging**
