### PR TITLE
[52] Develop a Contact Form Page using HTML

### PR DESCRIPTION
**Pull request by cherishebojudah**
## Task: `[52] Develop a Contact Form Page using HTML`
- `I created a contact form using HTML
Screenshot (108)
`

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Haven't you done `index.html` task before during HTML task?

**Comment by cherishebojudah** [comment]
I did. But I had a  problem referencing the file path for the index page because it's in another folder. So I copied it into the folder with the the contact and sign up pages.

**Comment by adaugochi** [comment]
That isn't done that way. You need to reference the path like this `../HTML Folder name/index.html`

**Comment by cherishebojudah** [comment]
Thank you ma'am. Done. Kindly review so I can create another PR for my second task.

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
