### PR TITLE
[DJFS-153]Article Publishing Endpoints

### PR DESCRIPTION
**Pull request by MYKEL7**
## Task: `[DJFS-153]Article Publishing Endpoints
- `Created an article publishing endpoints using Slim`

### CODE REVIEW

**Review by adaugochi — APPROVED** [review]
A job well done

**Comment by MYKEL7** [comment]
> A job well done

Thanks @adaugochi

**Comment by MYKEL7** [comment]
> A job well done

Thanks @adaugochi

**Comment by MYKEL7** [comment]
> A job well done

Thanks @adaugochi

**Pull request merged**
