### PR TITLE
[DCFS-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by kemysola**
## Task: `Product page including product images, product price and description.`
- `
Screen Shot 2021-02-17 at 9 42 47 AM

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @kemysola 

This task should be just purely `html` no `css` should be applied to it

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@kemysola You have other scholar's files in your pull request that you deleted. You should not be deleting other scholar's files. You need to revert them.

**Comment by kemysola** [comment]
> @kemysola You have other scholar's files in your pull request that you deleted. You should not be deleting other scholar's files. You need to revert them.

Good day, they have been reverted.Kindly assist in reviewing ma. @ToluAkin .

**Comment by ToluAkin** [comment]
@kemysola Kindly work on the comment from @adaugochi

**Comment by kemysola** [comment]
> @kemysola Kindly work on the comment from @adaugochi

@ToluAkin its been worked on ma, in my recent commit . Kindly review ma

**Review by adaugochi — CHANGES_REQUESTED** [review]
@kemysola click [here](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1238/files) to see the changes you have pushed.

You have pushed other people's work together with your task. And you haven't done the correction you were asked to do. I can still see CSS styling in your HTML code

**Comment by adaugochi** [comment]
I will have to close this PR since you created a new one

**Pull request closed without merging**
