### PR TITLE
[22] Newsletter Form Validation

### PR DESCRIPTION
**Pull request by Cynthia-Berry**
## Task: `[22] Newsletter validation`
- `The newsletter in the footer were validated`
newsletternewsletter2

### CODE REVIEW

**Comment by Cynthia-Berry** [comment]
@ToluAkin  and @adaugochi . Good Day.

The kindly merge my pull request.
The codeFactor error i am getting are from the `/` in the email regex which are definitely needed for the email validation.
Kindly advice on how to handle that Please.

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Cynthia-Berry You need to update the regex. I know you have been working on this all day, you are probably tired and frustrated but everything has to be done right. Well done!

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Cynthia-Berry Good Job! Lastly, you need to link the is file to all the pages. The newsletter is in all the pages.

**Comment by Cynthia-Berry** [comment]
@ToluAkin Hello Ma.
From What I have on my local repo. All files are properly linked. My guess on why you can't see it is because i deleted the first PR i created on this task .

Thank You

**Comment by ToluAkin** [comment]
@Cynthia-Berry I mean the js file to validate the newsletter needs to be linked to all the pages

**Review by ToluAkin — APPROVED** [review]

**Pull request merged**
