### PR TITLE
html-task

### PR DESCRIPTION
**Pull request by Lolatech07**
## Task: `Introduction to HTML Task`
- `Submission of HTML Task`

### CODE REVIEW

**Comment by adaugochi** [comment]
Hello. The title of your PR is wrong. Please follow the instructions given

**Comment by adaugochi** [comment]
You need to close the PR and create a new one with the right title. Also, your HTML task is expected to have 2 images. But, it seems that wasn't included in this PR.

**Comment by Lolatech07** [comment]
> You need to close the PR and create a new one with the right title. Also, your HTML task is expected to have 2 images. But, it seems that wasn't included in this PR.
> 
> Here is the link to the task https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/issues/7

Hi. Thanks for the task link. I didn't get this earlier. The 2 images were included in the task. I'm not sure why you're not seeing them.

**Comment by Lolatech07** [comment]
> You need to close the PR and create a new one with the right title. Also, your HTML task is expected to have 2 images. But, it seems that wasn't included in this PR.
> 
> Here is the link to the task https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/issues/7

Hi. I think I have successfully made the changes requested. If you please review my PR. Thanks.

**Pull request closed without merging**
