### PR TITLE
about-me

### PR DESCRIPTION
**Pull request by opeyemipeter1759**
## Task: [1] My First Pull Request`
- `Changes you made to given task`

### CODE REVIEW

**Comment by adaugochi** [comment]
Hello @opeyemipeter1759 
Well done. 
But your title ought to be `[1] My First Pull Request` as stated in the task. Instead, you decided to name the title of the PR `about me`

**Comment by adaugochi** [comment]
You have to close this PR and create a new one

**Comment by opeyemipeter1759** [comment]
Yes I was asked to closed it because I didn't follow the task instructions, then I created another one to correct the previous

**Comment by opeyemipeter1759** [comment]
@adaugochi

**Pull request closed without merging**
