### PR TITLE
[13] style up product page using CSS

### PR DESCRIPTION
**Pull request by yusrah247**
## Task: `[13] style up product page using CSS`
- `added two images to the image folder
product page styling using CSS`

3a

8a

### CODE REVIEW

**Comment by adaugochi** [comment]
Well done.

But, this `https://user-images.githubusercontent.com/42994369/92990824-5fc34480-f4d7-11ea-9abf-d98c87a1b7e9.jpeg` doesn't look that good. The input field within the card has some space by the right

**Review by ToluAkin — APPROVED** [review]

**Comment by yusrah247** [comment]
error fixed

**Comment by adaugochi** [comment]
Can you upload a picture of the fix?

**Comment by ToluAkin** [comment]
@yusrah247 You need to re-upload a screenshot of the fixed section

**Comment by yusrah247** [comment]
8b

**Comment by yusrah247** [comment]
8b

**Comment by yusrah247** [comment]
8b

**Comment by yusrah247** [comment]
Screenshot uploaded

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
