### PR TITLE
[64] Style the Product Details Page using CSS

### PR DESCRIPTION
**Pull request by DamisiM**
## Task: `[64] Style the Product Details Page using CSS`
- `Product Page`

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
kindly add screenshot of your work

**Comment by DamisiM** [comment]
IMG_20210113_140719

IMG_20210113_140707

**Comment by adaugochi** [comment]
Kindly upload that of mobile view

**Comment by DamisiM** [comment]
IMG_20210113_163801
IMG_20210113_163747
IMG_20210113_163816

**Comment by adaugochi** [comment]
This images you uploaded aren't mobile view

Kindly using `Snipping Tool` if you are on windows to screenshot images. Or you can use your keyword command - Press the `window button` and `prt sc button` together

**Comment by DamisiM** [comment]
product p1
product p2
product p3
product p4

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
