### PR TITLE
Add about me file

### PR DESCRIPTION
**Pull request by Whaleeey**
## Task: `Upload about me file
- `Add descriptions about Olawale

### CODE REVIEW

**Review by BenjaminKamena — CHANGES_REQUESTED** [review]
create a folder inside OlawaleGannyDauda, called aboutMe and then inside this folder put about.txt file and name you PR is not correct. Kindly check the criteria number 10 of your task and see what you are asked to use as PR title or name

**Comment by adaugochi** [comment]
Also, if you are for Dufuna-Fem, kindly clone this repo https://github.com/Dufuna-CodeCamp/Dufuna-Fem not Dufuna-CodeCamp20

**Comment by adaugochi** [comment]
Ensure to close this PR

**Comment by adaugochi** [comment]
Wrong PR title

**Pull request closed without merging**
