### PR TITLE
[7]  Develop a Contact Form Page using HTML

### PR DESCRIPTION
**Pull request by marindotib**
contact page impl

### CODE REVIEW

**Comment by marindotib** [comment]
> Please create a separate folder called `html-forms` for this task. The `contact.html` should be inside the `html-form` folder and the `html-form` folder should be inside your named folder

From the instruction given  for the
instruction
 contact form the file should be inside html file

**Comment by marindotib** [comment]
> Please create a separate folder called `html-forms` for this task. The `contact.html` should be inside the `html-form` folder and the `html-form` folder should be inside your named folder

From the instruction given the contact form is suppose to be inside the html form

**Comment by ToluAkin** [comment]
@marindotib Apologies for the confusion, the contact form should be in the htmlForm folder

**Comment by adaugochi** [comment]
Hello. You need to create one file for this task, which is contact form page.

**Comment by adaugochi** [comment]
View your changes yourself https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/220/files and see the files change. Also, the contact page should be inside your `html-forms` folder

**Pull request merged**
