### PR TITLE
[53] Develop a Contact Form Page using HTML

### PR DESCRIPTION
**Pull request by Oluwabusiolami**
## Task: `Name of given task`
- `Changes you made to given task`
Screenshot of Implementation

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Kindly ensure that your filenames or folder names don't contain spaces. replace the space with `-` or `_`

**Comment by Oluwabusiolami** [comment]
> Kindly ensure that your filenames or folder names don't contain spaces. replace the space with `-` or `_`

Done

**Review by adaugochi — CHANGES_REQUESTED** [review]
You created two contact page form. one of the files is called `contactform.html` and the other is `contact.html`. kindly delete one and leave the one that is ok

**Comment by Oluwabusiolami** [comment]
> You created two contact page form. one of the files is called `contactform.html` and the other is `contact.html`. kindly delete one and leave the one that is ok

Ok. Thank you

**Comment by Oluwabusiolami** [comment]
> You created two contact page form. one of the files is called `contactform.html` and the other is `contact.html`. kindly delete one and leave the one that is ok

Done. Kinly review

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
