### PR TITLE
[44]Product Page using Html

### PR DESCRIPTION
**Pull request by gracioust**
## Task: `Changes made to the ecommerce website `
- `Removed unnecessary pictures and avoided spacing the images name `
Capture 1
Capture 2
Capture 3

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
You are expected to make use of two images for this task.

**Comment by gracioust** [comment]
I don't understand, I only use two images in the website, which is the
mannequin and the sewing machine. We were ask to drop screenshot of the
website in the PR description that is why I added 3 screenshot images to
the PR

**Comment by adaugochi** [comment]
Remove other images that are not been used

**Comment by gracioust** [comment]
i want to make a new PR

**Pull request closed without merging**
