### PR TITLE
[12] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by kazeemerinfolami**
## Task: `[12] Style the Contact Us Page using CSS`
- `Style the Contact us page`
Screen Shot 2020-10-31 at 3 41 33 PM
Screen Shot 2020-10-31 at 3 41 38 PM
Screen Shot 2020-10-31 at 3 41 23 PM
Screen Shot 2020-10-31 at 3 41 26 PM
Screen Shot 2020-10-31 at 3 41 15 PM
Screen Shot 2020-10-31 at 3 41 05 PM

### CODE REVIEW

**Comment by adaugochi** [comment]
Kindly fix conflict on this PR. if you don't know how kindly reach out

**Comment by kazeemerinfolami** [comment]
Please how will I fix it?

**Comment by adaugochi** [comment]
- First checkout back to `master`
- Pull from upstream (I believe you should know this if you don't let me know)
- Checkout back to your working branch
- Then merge what is on `master` to your current working branch by running the command `git merge master`
- Add
- Commit
- And finally push

**Comment by adaugochi** [comment]
I hope this helps

**Pull request closed without merging**
