### PR TITLE
[10]Create & Style the Customer Signup Page using CSS

### PR DESCRIPTION
**Pull request by kazeemerinfolami**
## Task: `[10] Create & Style the Customer Signup Page using CSS`
- `CSS_signup`
Screen Shot 2020-10-22 at 3 04 17 PM
Screen Shot 2020-10-22 at 3 04 23 PM
Screen Shot 2020-10-22 at 3 04 52 PM

### CODE REVIEW

**Comment by adaugochi** [comment]
kindly fix codefactor issue. Also, this doesn't look like what you were asked to design. kindly, design what's on the mockup

**Comment by adaugochi** [comment]
Kindly send a screenshot of your design

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@kazeemerinfolami You have not designed the signup page according to the task design. Kindly update.

**Comment by kazeemerinfolami** [comment]
please I am confused, am I suppose to build a sign-in page/ a signup page??
because the sample link given is a login page: https://zpl.io/VKRBQ3P so it's confusing.. should I build my signup UI page as the diagram below? even when the task diagram is a sign-in page
Screen Shot 2020-10-26 at 10 07 00 PM

**Comment by kazeemerinfolami** [comment]
Good morning, now I know the problem, I got this message when I clicked on the link "You’re not invited to this project
Please contact project members."

**Comment by ToluAkin** [comment]
@kazeemerinfolami Have you requested for invite? Do you have access now?

**Comment by kazeemerinfolami** [comment]
Yes, I am currently working on the task

**Pull request closed without merging**
