### PR TITLE
[1]My First Pull Request

### PR DESCRIPTION
**Pull request by elizabethbusola**
## Task: Uploaded my goals
1) I have updated the title of my pull request
2) and I have also added what I plan to achieve at the end of the Dufuna-CodeCamp

### CODE REVIEW

**Comment by elizabethbusola** [comment]
kindly check, I think I have done what you asked me to do.

**Comment by elizabethbusola** [comment]
Am I permitted to create a new pull request because I am confused on how to
do the update needed to be done.

**Comment by elizabethbusola** [comment]
> Well done on making your first pull request.
> 
> * You need to update the title of your pull request to `[1] My First Pull Request`
> * You need to update the description of your pull request.
> * Update the content of your text file to include `Inside the txt file tell us what you hope to achieve at the end of this program`

I have done all that needed to be done

**Comment by ToluAkin** [comment]
You shouldn't open a new pull request. All you need to do is update the name of your pull request. 

On the same line as the name of your pull request, there is an edit button there to update the name.

**Comment by elizabethbusola** [comment]
I have done it, I did that after I sent that mail
Kindly check again

**Pull request closed without merging**
