### PR TITLE
 [CSFS-5] Create & Style the Customer Signup Page

### PR DESCRIPTION
**Pull request by Oge-nna**
## Task: ` [CSFS-5] Create & Style the Customer Signup Page `
- `Created and styled a responsive customer signup page`

SignUp
SignUp2
SignUpMobile
SignUpMobile2
SignUpTab
SignUpTab2

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done,

But, you have to place all images inside the `images` folder that is in your `html` folder.
Also, remove spaces on image names. replace with an `-` or an `_`

**Comment by Oge-nna** [comment]
> Well done,
> 
> But, you have to place all images inside the `images` folder that is in your `html` folder.
> Also, remove spaces on image names. replace with an `-` or an `_`

Hi @adaugochi, done. Thank you.

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Oge-nna Remove the images that you are not using for this task from the PR.

**Comment by Oge-nna** [comment]
> @Oge-nna Remove the images that you are not using for this task from the PR.

HI @ToluAkin done.

**Review by adaugochi — APPROVED** [review]

**Review by ToluAkin — APPROVED** [review]

**Pull request merged**
