### PR TITLE
[10] Create & Style the Customer Signup Page using CSS

### PR DESCRIPTION
**Pull request by faithakinbobola**
## Task: `[10] Create & Style the Customer Signup Page using CSS`
Screenshot (194)
Screenshot (195)
Screenshot (197)
Screenshot (198)
Screenshot (199)
Screenshot (200)

### CODE REVIEW

**Comment by adaugochi** [comment]
Is there a reason why you delete you contactForm.html page?

**Comment by faithakinbobola** [comment]
I made changes on it already and i was not done. I cut it ,pushed the sign up task first then paste it back. Does this affect it in any way?

**Comment by adaugochi** [comment]
ok...but, when you paste it. Did you also push it along

**Comment by faithakinbobola** [comment]
No. Should i push it?

**Comment by adaugochi** [comment]
Well, you can push along with your next task.

**Pull request merged**
