### PR TITLE
[12] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by opeyemipeter1759**
## Task: `Name of given task`
- `Changes you made to given task`
image

image

image

image

image
image
image
image

image

### CODE REVIEW

**Comment by adaugochi** [comment]
Well done.

In the mobile view image, the forms do not look centralize within the card

**Comment by opeyemipeter1759** [comment]
i have worked on it now. thanks

**Comment by opeyemipeter1759** [comment]
@adaugochi i have pushed the new changes. thanks

**Comment by adaugochi** [comment]
Nice, I still feel you can do better though. Image 5, I am still not satisfied

**Comment by opeyemipeter1759** [comment]
@adaugochi, alright, but which of the images is image5

**Comment by adaugochi** [comment]
Image number 5 that you posted

**Comment by opeyemipeter1759** [comment]
which of the images are you referring to?

**Comment by adaugochi** [comment]
https://user-images.githubusercontent.com/63324192/91860872-09c1e780-ec21-11ea-8089-2428d896c5ae.png

**Comment by opeyemipeter1759** [comment]
@adaugochi what about now. i have made changes .

**Comment by adaugochi** [comment]
https://user-images.githubusercontent.com/63324192/91860872-09c1e780-ec21-11ea-8089-2428d896c5ae.png

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
