### PR TITLE
[54] Add Page Navigation to your Pages- Fullstack

### PR DESCRIPTION
**Pull request by AAOYV2020**
…t page

## Task: `HTML Forms- adding navigation to contact form, sign up form and produc…`
- `Created contact page and sign up page, added navigation to all pages including product page`

### CODE REVIEW

**Review by adaugochi — COMMENTED** [review]
This is what task 54 says 
image


I don't know why you are creating signup page and contact page. Before task 4, You ought to have worked on two pages, which are product and contact form pages. All you are supposed to do here is to link these two pages together

**Comment by adaugochi** [comment]
Hello @AAOYV2020 So, I just noticed that you didn't see task 51 as part of your task that why you did what you did. So, task 51 (creating of contact form) comes first before task 54. The issue has been fixed now. You can now work on task 51 now before this. Kindly close this PR before you do that.

Have a great day

**Comment by AAOYV2020** [comment]
Thank you adaugochi, for your feedback. I must admit I'm a little confused. Please, I need a bit more clarification. Task 54 was what came up on the HTML- Forms task. Please, where can I find the selection criteria list for Task 51?
Also, if it entails creating a contact form, have I not already done that? Kindly let me know what exactly is required of me at this point? Thank you

**Comment by AAOYV2020** [comment]
Thank you, adaugochi. I have now seen the git link in the app.

**Pull request closed without merging**
