### PR TITLE
[54]Add Page Navigation to your Pages-Fullstack

### PR DESCRIPTION
**Pull request by Moronke02**
## Task: `Add Page Navigation to your Pages-Fullstack`
- `Added Navigation to the pages`
Screenshot (319)

### CODE REVIEW

**Comment by adaugochi** [comment]
Your branch has a conflict. You need to resolve it. 

Meanwhile, I noticed that you are working on contact form in this task. Contact form is for task [52]

**Comment by Moronke02** [comment]
> Your branch has a conflict. You need to resolve it.
> 
> Meanwhile, I noticed that you are working on the contact form in this task. Contact form is for the task [52]
@adaugochi, thanks for the feedback. please on which branch am I to work on. My vscode crashed and I tried re-installing only for me to discover that I lost the content in my HTML folder. So I tried rewriting the index.html for the product page which is presently the conflicting file. So, please what am I supposed to do concerning it?Thanks

**Comment by adaugochi** [comment]
oh, that's bad. Sorry about that.

Kindly check the last two pinned messages on the #git-versioncontrol channel. One of them talked about how to resolve conflict.
If you still don't get what to do, or how to go about me, kindly reach out

**Comment by Moronke02** [comment]
Tried Resolving the merging conflicts
Screenshot (339)

**Comment by Moronke02** [comment]
Added Navigation to the Pages
Screenshot (340)
Screenshot (342)

**Comment by adaugochi** [comment]
Long over due

**Pull request closed without merging**
