### PR TITLE
[8] Add Page Navigation to your Page

### PR DESCRIPTION
**Pull request by Olawumi11**
## Task: `To add page navigation`
- `Added links to all pages for easy navigation

`

### CODE REVIEW

**Comment by Olawumi11** [comment]
-Does this means I will have both contact form and product page in separate new folder, with both showing the navigation links to the pages? 
-or will I add it to the already created HTMLforms  folder?
- is there a specific name I am supposed give the folder?

**Comment by ToluAkin** [comment]
> -Does this means I will have both contact form and product page in separate new folder, with both showing the navigation links to the pages?
> -or will I add it to the already created HTMLforms folder?
> 
> * is there a specific name I am supposed give the folder?

@Olawumi11 No new separate folders, just edit the the ones you've created already.

**Comment by Olawumi11** [comment]
I couldn't find them again after I pulled upstream.

**Comment by ToluAkin** [comment]
> I couldn't find them again after I pulled upstream.

Checkout back to the task's branch. You pulled upstream on master branch, your added files does not exist on master

**Comment by Olawumi11** [comment]
I did exactly that  ma, right before I even made the pull request. After pulling upstream I checked out into a new branch from the master, and only Ideas folders were there in my task folders. The tasks were not available.

**Comment by Olawumi11** [comment]
What do I do?

**Pull request closed without merging**
