### PR TITLE
[16] Render the related product list on the HTML with JAVASCRIPT

### PR DESCRIPTION
**Pull request by opeyemipeter1759**

### CODE REVIEW

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@opeyemipeter1759 Your javascript file is not linked to any page.

**Review by ToluAkin — CHANGES_REQUESTED** [review]
Did you test this and get the expected result? There is no way this would run...

**Review by adaugochi — CHANGES_REQUESTED** [review]
I wonder if this code ran successfully before you push this code to be reviewed. Try figuring out what you did wrong
image

**Comment by opeyemipeter1759** [comment]
@ToluAkin i have effected the correction.

**Review by ToluAkin — APPROVED** [review]
Well done!

**Pull request merged**
