### PR TITLE
Add about me file

### PR DESCRIPTION
**Pull request by Mayowa2020**
## Task: `"Upload About me File"
-Add descriptions about Bukky Oyetimehin

### CODE REVIEW

**Review by BenjaminKamena — APPROVED** [review]

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Weldone @Mayowa2020 

From the criteria attached to this task, you are expected to create a folder titled aboutMe in the folder that has your name as the title. Then you place the aboutMe.txt file in it. Kindly make this correction.

**Review by Ireti203 — COMMENTED** [review]
Your PR is not properly titled. Kindly name your PR appropriately following the instructions in the task criteria. You ought to have a number in square brackets followed by "About Me". Kindly follow the title given in the task criteria..

**Comment by Mayowa2020** [comment]
Hello Ireti,

Not sure what you mean by this. Have done my pull request again following
the instructions as directed both in the slides and video, but did not see
anything as stated 'You ought to have a number in square brackets followed
by "About Me"".

Kindly be of help as I have sent in another pull request.

Thank you.

**Comment by adaugochi** [comment]
@Mayowa2020 

Kindly take a look at criteria 10 
image

Does your task make mention of something like that

**Comment by adaugochi** [comment]
Also, if you are for Dufuna-Fem, kindly clone this repo https://github.com/Dufuna-CodeCamp/Dufuna-Fem not Dufuna-CodeCamp20

**Comment by adaugochi** [comment]
Ensure to sure this PR

**Pull request closed without merging**
