### PR TITLE
[1] My First Pull Request 

### PR DESCRIPTION
**Pull request by Samju200**
## Task: `upload About me file`
- `what i want to achieve at the end of the program   `

### CODE REVIEW

**Comment by Samju200** [comment]
My first pull request

**Comment by Samju200** [comment]
> Well done on creating your first pull request. I think there are some things that would make it better.
> 
> * You need to create your details in the submissions folder
> * You should rename your pull request to `[1] My First Pull Request`
> * You could update the content of your text file to include your name

**Comment by Samju200** [comment]
Okay 
Where is the submissions folder because i can't find it
Thank you

**Comment by ToluAkin** [comment]
Another PR has been made and merged.

**Pull request closed without merging**
