### PR TITLE
[145] Create & Style the Customer Signup Page using CSS

### PR DESCRIPTION
**Pull request by Nurmalee**
## Task: [145] Create & Style the Customer Signup Page using CSS
- created and styled my e-commerce customer sign-up page
desktop-view-FULL
tablet-view-FULL
mobile-view-A
mobile-view-B

### CODE REVIEW

**Comment by Nurmalee** [comment]
@adaugochi @ToluAkin @TundeOladejo

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @Nurmalee 

Kindly place your `signup.html` inside `html-forms` folder instead

**Comment by Nurmalee** [comment]
> Well done @Nurmalee
> 
> Kindly place your `signup.html` inside `html-forms` folder instead

@adaugochi  I have just done that.. thanks ..

**Review by adaugochi — APPROVED** [review]
I love your design @Nurmalee

**Comment by Nurmalee** [comment]
> I love your design @Nurmalee 

@adaugochi thank you very much... I'm motivated...🤗

**Pull request merged**
