### PR TITLE
LeetCode #1087

### PR DESCRIPTION
**Pull request by harshsri28**
## Task: `Leetcode`
- `Add the screenshot as well as code snippet of mentioned program in task`
-  [https://drive.google.com/drive/folders/17N25S9AeRX1QiydTMRJvupwQieK8fN1o?usp=sharing](url)
googledoc

### CODE REVIEW

**Comment by harshsri28** [comment]
If any formatting is required , kindly inform.

**Review by Ireti203 — CHANGES_REQUESTED** [review]
@harshsri28 Kindly remove the spaces in your file/folder names. e.g Searching Algorithm folder

**Comment by harshsri28** [comment]
i updated all files/folder name.

Kindly accept my pr.

**Comment by harshsri28** [comment]
> @harshsri28 Kindly remove the spaces in your file/folder names. e.g Searching Algorithm folder

i updated folder name

**Review by adaugochi — CHANGES_REQUESTED** [review]
Hi...

This repo is for those undergoing a training program with us.

**Pull request closed without merging**
