### PR TITLE
[20] Sign-Up Form Validation

### PR DESCRIPTION
**Pull request by Samju200**
## Task: `validation of Signup form`
- `Changes you made to given task`

### CODE REVIEW

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Samju200 Why is `nameValidation` seperated from `fieldValidation`? What is the difference?

**Comment by Samju200** [comment]
> @Samju200 Why is `nameValidation` seperated from `fieldValidation`? What is the difference?

@ToluAkin i just want to separate the name from other field. but have change it now. 
Thank you

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Samju200 There are error from the regex. You need to resolve that.

**Comment by Samju200** [comment]
> @Samju200 There are error from the regex. You need to resolve that.

@ToluAkin i have  change the password regex again  and it is working here.

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Samju200 The code tester isn't saying the regex is wrong but there are characters that are not needed that is in the regex.

**Comment by Samju200** [comment]
> @Samju200 The code tester isn't saying the regex is wrong but there are characters that are not needed that is in the regex.

@ToluAkin Okay.
Done. Thank You

**Review by ToluAkin — APPROVED** [review]

**Pull request merged**
