### PR TITLE
[62] Create and Style the Customer Sign up page using CSS

### PR DESCRIPTION
**Pull request by Tocyn**
Screen Shot 2020-10-23 at 4 34 36 PM

### CODE REVIEW

**Comment by adaugochi** [comment]
Well done @Tocyn 

But, you still need to improve on your design. I believe you can do more better than what you have. Kudos

**Comment by Tocyn** [comment]
Thank you @adaugochi, what part of the design do you want me to review?

**Comment by adaugochi** [comment]
The footer and the form card

**Comment by Tocyn** [comment]
Screen Shot 2020-10-27 at 12 35 11 AM
Screen Shot 2020-10-27 at 12 34 55 AM

**Comment by Tocyn** [comment]
Screen Shot 2020-10-27 at 6 20 40 AM
Screen Shot 2020-10-27 at 6 37 18 AM

**Comment by adaugochi** [comment]
There are spaces left and right for this to occupy. It looks shrink. Make it to take available spaces
https://user-images.githubusercontent.com/70757475/97261359-f39a6700-181e-11eb-80b0-b44b4af0688d.png

**Comment by Tocyn** [comment]
Screen Shot 2020-10-28 at 7 29 50 AM

**Comment by adaugochi** [comment]
Well done @Tocyn 

We are making progress. Kindly still work on your footer section

**Comment by Tocyn** [comment]
Screen Shot 2020-10-28 at 5 45 41 PM

**Comment by adaugochi** [comment]
I still think you can put some more effort into giving your footer a better look. Well done

**Comment by Tocyn** [comment]
Thanks @ Maryfaith, better look in what aspect, I am not clear on what you
want me to do.
Thanks again.

**Comment by adaugochi** [comment]
content within the footer looks compressed. no padding effect on the left. The input field and button are not styled

**Comment by adaugochi** [comment]
So, look at the mockup and what you did. compare the difference and see how you can improve on it

**Comment by Tocyn** [comment]
Screen Shot 2020-10-31 at 12 42 41 AM
Screen Shot 2020-10-31 at 12 40 44 AM

**Comment by adaugochi** [comment]
On mobile screen, all the padding inside the form-card is no longer there

**Comment by Tocyn** [comment]
Screen Shot 2020-11-02 at 2 55 25 PM

**Pull request closed without merging**
