### PR TITLE
[DFMD-1] My First Pull Request

### PR DESCRIPTION
**Pull request by Peace-Peter**
## Task: `Upload About Me File`
- Added description about Peace

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Also, you pushed two `AboutMe.txt`fiels 
image

Remove the one that doesn't have `AboutMe` folder.  Also the space from the `About Me` folder

**Comment by Peace-Peter** [comment]
Good evening. Thanks for the corrections.

Will I need to create a new pull request? Or just delete it in the local
repository?

**Comment by adaugochi** [comment]
> **Say for instance a Mentor comment of your PR, how do I go about it? How will the update be reflected on the Pull Request I already created? Below is a step to follow:**

- Still, on that same branch, update your changes.
- Add your changes (`git add .`).
- Commit your changes (`git commit  -m  "commit message"`).
- Finally, Push your change (`git push origin branch_name`)

@Peace-Peter

**Comment by adaugochi** [comment]
You are for `Dufuna fem` not `Dufuna code camp`. You aren't supposed to fork this repo. Going forward I will have to close this PR. KIndly fork this repo (https://github.com/Dufuna-CodeCamp/Dufuna-Fem) instead

**Pull request closed without merging**
