### PR TITLE
Add Aboutme file

### PR DESCRIPTION
**Pull request by HalimahOladimeji**
My name is Halimah and I am 20 years old.

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @HalimahOladimeji 

But, we didn't follow certain instructions require of you to do in the task.

Inside your name folder (i.e HalimaOladimeji), you are expected to create an `aboutMe` folder. Inside the `aboutMe`, create a txt file and write about yourself there.

Also, the title of your pull request didn't follow the order that is stated in the task.
Moreso, don't work on the master branch. create a new working branch for every task you are working on.
Kindly close this pull request and create a new one.

**Comment by adaugochi** [comment]
To close a pull request, kindly scroll to the bottom of this page you will see 
image

**Comment by HalimahOladimeji** [comment]
Hello good afternoon.
I am not done with my task yet. I did not know it's been submitted. I'm so
sorry.
I already posted a message on slack saying I have issues with creating
another folder inside the submissions folder. But no one replied me. Can
you explain how I can do that? I only saw how to add a file and not a
folder. Kindly help me. Thank you.

**Comment by adaugochi** [comment]
The way you created your name folder is the same way you have to do this also

**Pull request closed without merging**
