### PR TITLE
[7] Develop Contact Form Page using HTML

### PR DESCRIPTION
**Pull request by Cynthia-Berry**
## Task: `[7] Develop Contact Form Page using HTML`
-            `Developed contact page and linked navigations`
contact1
contact2

### CODE REVIEW

**Comment by adaugochi** [comment]
Well done.

**Comment by adaugochi** [comment]
Well done.

Please remove the space on your folder name. `HTML Form` - this is wrong. `HTMLForm` or HTML-Form` is ok.

**Comment by Cynthia-Berry** [comment]
Hello @adaugochi . Thank you .
I have effected the changes as instructed.
Kindly review and approve.

Thank you

**Comment by adaugochi** [comment]
Hello, You have two contact.html files now. One inside the `HTML-form` folder and the other inside the HTML form` folder. Please delete the `HTML form` folder. I only ask that you rename not creating a whole new folder

**Comment by Cynthia-Berry** [comment]
Hello @adaugochi .
please i need your help on this.
I only renamed the folder.
Checkout to master, Pulled upstream master
checked out to my branch and pushed the changes.

I don't know why 2 folders are showing.
Kindly advice on what went wrong

**Comment by adaugochi** [comment]
what you should have done is.
- Make your changes on the current branch
- Add, commit
- checkout to master
- pull upstream
- checkout back to your working branch
- run `git merge master` : only if you pulled a change from master
- Add and commit again: only if you ran git merge
- finally push

**Comment by Cynthia-Berry** [comment]
Thank you for your swift response.
I really do appreciate

**Comment by Cynthia-Berry** [comment]
Hello @adaugochi 
I am so sorry for the inconvinences.

Please what do the below statement imply
run `git merge master` : only if you pulled a change from master
Add and commit again: only if you ran git merge

**Pull request merged**
