### PR TITLE
[40] Calculate Product Shipping Cost 

### PR DESCRIPTION
**Pull request by pelumi454**
## Task: `Calculate Product Shipping Cost `
- `Changes you made to given task`

### CODE REVIEW

**Review by adaugochi — COMMENTED** [review]
Why does your task look so similar to a task that I have approved before? I want to believe that you don't copy other people task

**Comment by adaugochi** [comment]
Post picture of the result you got

**Comment by adaugochi** [comment]
image
 For start to finish is exactly the same. Why is that so? Prior to when I approve hers, I believe I already approve something similar

**Comment by pelumi454** [comment]
Screenshot (71)
Screenshot (72)

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
