### PR TITLE
[46] Product Page using HTML

### PR DESCRIPTION
**Pull request by Goldochim**
MY PAGE 1
MY PAGE 2
MY PAGE 3

## Task: `HTML Product task`
- `Changes you made to given task`

### CODE REVIEW

**Review by ToluAkin — CHANGES_REQUESTED** [review]
@Goldochim Your file name needs to have extension `.html`
Use relative path to link your images. check [here](https://www.w3schools.com/Html/html_filepaths.asp) on how to do that.
Remove all width and height from images. You will style when your course study gets to CSS.
You need to add the images  used. You are also meant to use only 2 product images in your page.

**Comment by adaugochi** [comment]
You can't change your PR title like that. You already made mistake. You have to close this PR and create a new one

**Review by adaugochi — CHANGES_REQUESTED** [review]
Where are the images you used for this task?

**Comment by Goldochim** [comment]
> @Goldochim Your file name needs to have extension `.html`
> Use relative path to link your images. check [here](https://www.w3schools.com/Html/html_filepaths.asp) on how to do that.
> Remove all width and height from images. You will style when your course study gets to CSS.
> You need to add the images used. You are also meant to use only 2 product images in your page.

okay ma'am. Will do that. Thank you

**Pull request closed without merging**
