### PR TITLE
[54] Add Page Navigation to Pages 

### PR DESCRIPTION
**Pull request by ayotola-t**
## Task: `HTML Forms Task`
- Created Sign Up and Contact Pages
- Added links to all navigation pages

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
This is what task 54 says 
image

I don't know why you are creating signup page and contact page. Before task 4, You ought to have worked on two pages, which are product and contact form pages. All you are supposed to do here is to link these two pages together

**Comment by ayotola-t** [comment]
Hello Ada,

I find your language a bit condescending. If I'm getting things wrong or interpreting tasks incorrectly, please tell me. This is my first time doing this and it is the strangest thing. I should be able to make mistakes, ask stupid questions. I'm open to correction. But there has to be some kind of respect.

That being said, before task 4, I only had a product page. I didn't create a contact page. I just reviewed that past task instructions and there is no instruction as to a contact form. If I was supposed to assume that a contact form was a regular feature, I can't. This is my first time coding. Also, I doubt my PR would have been approved if I didn't tick all the boxes. I am attaching a screenshot. 
IMG_7684
And if I don't know what it is you are even talking about, please point it out. 

In my last task there was a back and forth as to the number of images I used in my task. I had to ask specifically because I was so confused. There was no instruction as to that in the criteria. Maybe some of these things are assumed by the mentors but there isn't anyway in the world I would know that.

The acceptance criteria of the HTML Forms task included a product page, a contact page and a sign up form. Since there are only two pages (Product and Contact), on which page does the signup form go on please?

**Comment by ayotola-t** [comment]
I also decided to check other people's work. I am so stumped to what it is I have done differently. Please walk me through it. 

Screenshot 2020-10-05 at 9 25 19 PM
Screenshot 2020-10-05 at 9 25 26 PM
Screenshot 2020-10-05 at 9 25 52 PM

**Comment by adaugochi** [comment]
I meant task 54 and not 4 I have updated my statement.

Meanwhile, I don't understand what you meant by `I find your language a bit condescending.` Cos to me I was trying to explain the task you are meant to do to the simplest and painless of English so you understand me and I don't have to repeat the same thing. I don't know how you read the comment I dropped but I was trying to be plain with my comment for easy understanding

**Comment by adaugochi** [comment]
After the product page task, you ought to have task [52] - which is where you work on contact page task. Then next is task [54] - which is adding navigation links to the two pages you have created

**Comment by ayotola-t** [comment]
_"I don't know why you are creating signup page and contact page"_ is very different from _"Why are you creating a signup and contact page?"_ It really isn't up to you to like the word. Your language made me feel small and stupid. If anyone said that to you about your work, you wouldn't feel affirmed or nudged in the right direction. And now the 'mistake' I made isn't my mistake at all. 

HTML task was [45]. HTML Forms task was [54]. I have not come across task [52].

**What do you require I do now? What changes do I make to the task?**

Please do not out of your way to reply me outside your working hours. I didn't expect you to. I wanted to get the task out of the way. I have a full time job myself and I understand. I'll talk to you tomorrow. Have a good night.

**Comment by adaugochi** [comment]
Hello, 

`I don't know why you are creating signup page and contact page` - this simply means what is it. I don't know why you did what you did. Cos, I was confused about why you did that. It is now left for you to tell me `Ah, that's what I saw as my task`. Then I would know you didn't even have task 52, to begin with. Since you think you are right with what you said, well I have nothing else to say.


Meanwhile, I think you should reach out Nifemi (Dufuna CodeCamp) that for some reason you don't have task  [52] - creating a contact form. She should be able to help. Once she has done that, you have to close this PR and work on that task first before this one

**Pull request closed without merging**
