### PR TITLE
[DJFS-168] Create the Cart Page with REACT

### PR DESCRIPTION
**Pull request by Samju200**
cart2
cart1
cart3
## Task: `React App`
- `cart page

`

### CODE REVIEW

**Comment by Samju200** [comment]
@adaugochi  the check fail is from the test file made.
Thank you

**Comment by Samju200** [comment]
@ToluEnny24

**Comment by Samju200** [comment]
Good afternoon @ToluAkin  @adaugochi

**Comment by ToluEnny24** [comment]
Hi @Samju200 well done on your Pull Request. Can you send a message on slack to Tolulope, let's review together...

**Comment by Samju200** [comment]
> Hi @Samju200 well done on your Pull Request. Can you send a message on slack to Tolulope, let's review together...

Okay, Thank You for the reply.

**Pull request closed without merging**
