### PR TITLE
[21] Contact Form Validation

### PR DESCRIPTION
**Pull request by opeyemipeter1759**

### CODE REVIEW

**Comment by opeyemipeter1759** [comment]
@ToluAkin kindly review my PR

**Comment by adaugochi** [comment]
Try fixing the issue the automatic code review is pointing at

**Comment by opeyemipeter1759** [comment]
@adaugochi the auto code review is pointing to the regex string.

**Comment by adaugochi** [comment]
Read what the error says and find out why it is pointing it out

**Comment by adaugochi** [comment]
Other people has the same issue but were able to fix it

**Comment by opeyemipeter1759** [comment]
@adaugochi i have fixed it.

**Comment by adaugochi** [comment]
Well done @opeyemipeter1759 Please add a picture of what you did

**Comment by opeyemipeter1759** [comment]
image
image

**Comment by opeyemipeter1759** [comment]
> Well done @opeyemipeter1759 Please add a picture of what you did

@adaugochi done.

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
