### PR TITLE
[44] Product Page using HTML

### PR DESCRIPTION
**Pull request by Onyinye101**
## Task: `[44] Product Page using HTML`
- `This is an HTML-only product page for an E-commerce store`

Screenshot 2020-09-24 at 7 31 05 PM
Screenshot 2020-09-24 at 7 31 37 PM

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
I think you are required to just use two images for this task

**Comment by Onyinye101** [comment]
I used only two images for the task. Thank you.

**Review by adaugochi — COMMENTED** [review]
You are expected to make use of two images in this task and not 4. Also, create an `images` folder to place all the images there

**Comment by adaugochi** [comment]
This information should guide you 

> Say for instance a Mentor comment of your PR, how do I go about it? How will the update be reflected on the Pull Request I already created? Below is a step to follow:

-  Still, on that same branch, update your changes.

- Add your changes (git add .).

- Commit your changes (git commit  -m  "commit message").

- Finally, Push your change (git push origin branch_name)

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
