### PR TITLE
[21] Contact Form Validation

### PR DESCRIPTION
**Pull request by MYKEL7**
## Task: `Contact Form Validation`
- `Validated contact form`

contact

contact1

### CODE REVIEW

**Comment by adaugochi** [comment]
Try fixing the issue the automatic code review is pointing at

**Comment by MYKEL7** [comment]
Good morning, pls I don't get it,  the error it pointing at is the regEx
code. Should I remove the regeEx code or what should I do?

**Comment by adaugochi** [comment]
Read what the error says and find out why it is pointing it out. Other people has the same issue but were able to fix it. You can reach out to @opeyemipeter1759 on that

**Review by adaugochi — COMMENTED** [review]
Most of the implementation here is the same. Try as much as possible to ensure code reusability. All regex action and when it is empty can be handle in one function

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
